# Generated by Django 5.0.4 on 2024-05-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchedlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='final.film'),
        ),
    ]
